name:                rpn-calculator
version:             0.1.0.0
github:              "YOURUSERNAME/rpn-calculator"
license:             BSD3
author:              "Alberto"
maintainer:          "albamigh@gmail.com"
copyright:           "Copyright (c) YOURNAME"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Educational

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YOURUSERNAME/rpn-calculator#readme>

dependencies:
- base >= 4.7 && < 5
- text
- filepath
- containers
- acme-missiles

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  rpn-calculator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpn-calculator
    when:
    - condition: false
      other-modules: Paths_rpn_calculator

tests:
  rpn-calculator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpn-calculator
